### ISSUE TITLE
Addition of root to wheel group, as set by klusrmgr during install, breaks smbd startup

### ISSUE THREAD

**Issue by LewisR** [bitwiseworks/samba-os2#3]
When current (1.3.2) builds of klusrmgr are installed or updated, the wheel group is apparently created and root is added as the only member of this group. Unfortunately, when this happens, smbd fails to start:

```
Starting SMB services
  SMBD:     The process ID is 52
  NMBD:     The process ID is 53
Warning! smbd.exe apparently stopped.
Done.
```
End of log.smbd:
```
[2020/05/01 11:38:36.203000,  0] auth/auth_util.c:865(make_system_session_info_from_pw)
  create_local_token failed: NT_STATUS_NO_SUCH_USER
[2020/05/01 11:38:36.203000,  1] smbd/server.c:1260(main)
  ERROR: failed to setup system user info: NT_STATUS_NO_SUCH_USER. 
```
Removing root from wheel allows smbd to start.

I am not even going to ask why we need a wheel group. Surely, Fedora no longer uses wheel for sudoers (not that that should have any bearing on OS/2).

**Comment by herwigb** [comment]
Verified. Latest klusrmgr does not add group "wheel" anymore and installation removes any preexisting group "wheel". groupmod -x "wheel" fixes the problem. klUsMgr 1.4.0-1 executes that after installation.
